### ISSUE TITLE
tag-ur-it doesn't trigger on non-first events

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [damccorm/tag-ur-it#13]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

Should this get assigned to @damccorm?
**Assign to damccorm**: yes

## Issue Description

I work [here](https://github.com/NETMouse-projects/ABCNET/issues). I've changed my `issues.yml` to:
```
name: Labeler
on:
  issues:
    types: [opened, edited, pinned, unpinned, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: damccorm/tag-ur-it@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: "./IssueRules.yml"
```
But when I edit [this](https://github.com/NETMouse-projects/ABCNET/issues/47) issue no labels are added. Only first event works correctly.

**Comment by damccorm** [comment]
Right now, that's by design - the action just looks at the initial issue content. I can see why it might be desirable to look at other elements in the thread, but I can also see that being harmful or ambiguous. For example, if I have a thread with the following layout:

**comment 1**
`*Type*: FOO`

**comment 2**
`BAR`

and have the following configuration:
```
rules:
- valueFor: '*Type*'
  contains: FOO
  addLabels: ['FOO']

nomatches:
- contains: 'BAR'
  addLabels: ['BAR']
```

what should happen? Should I parse the entire output for the `nomatches` rule, or just parse comment 2 and add BAR.

All of that to say, this is by design for now, but I think this would be a good addition going forward
