### ISSUE TITLE
Label groups support or "groups" expression

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [damccorm/tag-ur-it#14]
## Required Information

Permit create label groups in `.yml` files.

**Question, Bug, or Feature?**  
*Type*: Feature

Should this get assigned to @damccorm?
**Assign to damccorm**: yes

## Issue Description

Code example:
```
groups:
  - labels:
    - groupA: ['label-A', 'label-B']

rules:
- valueFor: '**Example**'
  contains: 'Something'
  addLabelGroup: ['groupA']
```
The similar functionallity could be implemented for milestones:
```
groups:
  - milestones:
    - groupA: ['milestone-A', 'milestone-B']
```
